<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>bar</description>
   <name>seelItem</name>
   <tag></tag>
   <elementGuidId>7be4d35f-7e22-4e3e-8d9a-bd11253e1ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nav-xshop&quot;]/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
